using System.Collections.Generic;

namespace Abc.Core.Units {
    public static class Pressure {
        public static UnitInfo Measure = new( pressureName, pressureCode, null, pressureDef
            , new TermInfo(Mass.Measure.Id, 1)
            , new TermInfo(Distance.Measure.Id, -1)
            , new TermInfo(Time.Measure.Id, -2)
        );

        public static List<UnitInfo> Units =>
            new() {
                new UnitInfo( pascalName, pascalCode, null, pascalDef
                , new TermInfo(Mass.kilogramsName, 1)
                , new TermInfo(Distance.metersName, -1)
                , new TermInfo(Time.secondsName, -2)
                )
                , new UnitInfo(mmHgName, mmHgCode, null, mmHgDef
                , new TermInfo(Mass.mmHgMassName, 1)
                , new TermInfo(Distance.centimetersName, -1)
                , new TermInfo(Time.secondsName, -2)
                )
            };

        internal const string pressureName = "Pressure";
        internal const string pressureCode = "P";
        internal const string pressureDef = "Pressure is the force applied perpendicular to "
            +"the surface of an object per unit area over which that force is distributed.";
        internal const string pascalName = "Pascal";
        internal const string pascalCode = "Pa";
        internal const string pascalDef = "The pascal is the SI derived unit of pressure used to quantify pressure.";
        internal const string mmHgName = "Millimetre of mercury";
        internal const string mmHgCode = "mm[Hg]";
        internal const string mmHgDef = "A millimetre of mercury is a manometric unit of pressure, "
            + "formerly defined as the extra pressure generated by a column of mercury one millimetre high";
    }
}